// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxfBQ3KAMlHZm54BT4WayfrP0qYR1r74',
    appId: '1:298957259547:web:198c26b730242fdb2189be',
    messagingSenderId: '298957259547',
    projectId: 'flatsplit-b3837',
    authDomain: 'flatsplit-b3837.firebaseapp.com',
    storageBucket: 'flatsplit-b3837.firebasestorage.app',
    measurementId: 'G-JT1LDQSW1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0LolEC6XNEOxMFMrgKZH_uwZlwGbfb8w',
    appId: '1:298957259547:android:35aaf20cfd7cde6d2189be',
    messagingSenderId: '298957259547',
    projectId: 'flatsplit-b3837',
    storageBucket: 'flatsplit-b3837.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ljq2Yh_eiWCA7oPSxoa8iKEGrYjfDqI',
    appId: '1:298957259547:ios:e32f64c0253608e62189be',
    messagingSenderId: '298957259547',
    projectId: 'flatsplit-b3837',
    storageBucket: 'flatsplit-b3837.firebasestorage.app',
    iosBundleId: 'com.flatsplit.flatsplit',
  );
}
